### ISSUE TITLE
Valerian doesn't suck

### ISSUE THREAD

**Issue by valerian** [TheultimateZank/Riga-IntelligentSoftware#1]
maybe @valeriansaliou does, but not @valerian , please be more careful with your commit messages :)

**Comment by AlexisZankowitch** [comment]
Ah ah sorry didn't know that tags was actually working 😅

**Comment by valeriansaliou** [comment]
That's nice! Sorry to the short name @valerian for Alexis bothering you.

**Comment by AlexisZankowitch** [comment]
fixes :+1:
