### ISSUE TITLE
[INFO] RTU Riga

### ISSUE THREAD

**Issue by remiflament** [TheultimateZank/Riga-IntelligentSoftware#2]
Bonjour,
Ce code est toujours utilisé au sein du cours DevMethodsApplied en tant qu'exemple sur le projet final.
Bon par contre aucun crédit, je vous ai trouvé en regardant le dossier .git

**Comment by valeriansaliou** [comment]
Marrant! Tu viens de l'ENSSAT ou d'une autre école ? (UTC?)

**Comment by remiflament** [comment]
Ouai c'est sympa pour votre taff !
Non mon école c'est 3il sur Limoges, c'est une petite école 😌

Du coup je vais regarder un ce code même si il a un petit coup de vieux sur
le JS

**Comment by AlexisZankowitch** [comment]
@valeriansaliou  si tu retrounes sur Riga tu demanderas au prof qu'il nous file un carton de black balsam stp ? 👍
